# Generated by Django 4.2.28 on 2026-03-06 01:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Alumno', '0002_alter_alumno_table'),
    ]

    operations = [
        migrations.CreateModel(
            name='AsignacionCurso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('horario', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'asignacion_curso',
            },
        ),
        migrations.CreateModel(
            name='Catedratico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('profesion', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'catedratico',
            },
        ),
        migrations.CreateModel(
            name='Curso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('codigo', models.CharField(max_length=20, unique=True)),
                ('creditos', models.IntegerField()),
            ],
            options={
                'db_table': 'curso',
            },
        ),
        migrations.CreateModel(
            name='InscripcionAlumno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_inscripcion', models.DateField(auto_now_add=True)),
                ('alumno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Alumno.alumno')),
                ('asignacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Alumno.asignacioncurso')),
            ],
            options={
                'db_table': 'inscripcion_alumno',
            },
        ),
        migrations.CreateModel(
            name='Nota',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nota', models.DecimalField(decimal_places=2, max_digits=5)),
                ('inscripcion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Alumno.inscripcionalumno')),
            ],
            options={
                'db_table': 'nota',
            },
        ),
        migrations.AddField(
            model_name='asignacioncurso',
            name='catedratico',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Alumno.catedratico'),
        ),
        migrations.AddField(
            model_name='asignacioncurso',
            name='curso',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Alumno.curso'),
        ),
    ]
